[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pingouin>=0.5.5",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
